version: '3'

services:
  db:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=movies
#      - POSTGRES_USER=movies
#      - POSTGRES_DB=movies
    volumes:
      - C:\yandex_praktikum\postgres:/var/lib/postgresql/data/
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["/usr/src/app/entrypoint.sh"]
#    volumes:
#      - ./app/static:/usr/src/app/static
#      - ./app/media:/usr/src/app/media
#      - ./app/logs:/usr/src/app/logs
#      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

#
#  nginx:
#    build: docker/nginx
#    volumes:
#      - static_volume:/home/app/web/staticfiles
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./configs:/etc/nginx/conf.d:ro
#    ports:
#      - "80:80"
#    depends_on:
#      - web
#
#volumes:
#  postgres_data:
#  static_volume:

