version: '3'

services:
  postgres_db:
    container_name: postgres_db
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    env_file:
      - envs/postgres.env
    volumes:
      - ..\..\postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgres/file.backup:/file.backup
    networks:
      - movies_admin
    ports:
      - "5432:5432"

  django:
    container_name: django
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["/usr/src/app/entrypoint.sh"]
    volumes:
      - ./app/static:/usr/src/app/static
      - ./app/media:/usr/src/app/media
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - envs/django.env
    networks:
      - movies_admin
    depends_on:
      - postgres_db

  nginx:
    image: nginx:1.19.0-alpine
    container_name: nginx
    volumes:
      - ./app/static/:/static/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
    networks:
      - movies_admin
    depends_on:
      - django
      - postgres_db

networks:
  movies_admin:
